# Generated by Django 3.2.7 on 2021-09-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='chat_id')),
                ('chat_title', models.CharField(max_length=50, verbose_name='chat_title')),
                ('chat_messages_count', models.IntegerField(default=0, verbose_name='chat_messages_count')),
            ],
        ),
    ]
