# Generated by Django 3.2.7 on 2021-09-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_chat_id', models.IntegerField(verbose_name='from_chat_id')),
                ('from_user_id', models.IntegerField(verbose_name='from_user_id')),
                ('message_id', models.IntegerField(verbose_name='message_id')),
                ('message_text', models.CharField(max_length=250, verbose_name='message_text')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('user_name', models.CharField(max_length=50, verbose_name='user_name')),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.IntegerField(unique=True, verbose_name='chat_id'),
        ),
    ]
